export enum Technology {
  Typescript = 'Typescript',
  Javascript = 'Javascript',
  NextJS = 'NextJS',
  NodeJS = 'NodeJS',
  ReactJS = 'ReactJS',
  Tailwind = 'Tailwind',
  HTML = 'HTML',
  CSS = 'CSS',
  SASS = 'SASS',
  Bootstrap = 'Bootstrap',
  Git = 'Git',
  SQL = 'SQL',
  PostgreSQL = 'PostgreSQL',
  MySQL = 'MySQL',
  Jest = 'Jest',
  Playwright = 'Playwright',
  Solidity = 'Solidity',
  Figma = 'Figma',
  Python = 'Python',
  Django = 'Django',
  Web3JS = 'Web3JS',
}
